name: glitcher
description: Glitcher - Social App for Gamers!

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  fluttertoast: ^3.1.3
  flutter_svg: ^0.14.3
  firebase_storage: ^3.0.6
  image_picker: ^0.6.7+4
  path: ^1.6.2
  video_player: ^0.10.2+3
  chewie: ^0.9.10
  flutter_icons: 0.2.0
  youtube_player_flutter: ^7.0.0+7
  cloud_firestore: ^0.12.9+5
  toast: ^0.1.5
  audiofileplayer: ^1.1.1
  modal_progress_hud: ^0.1.3
  soundpool: ^0.5.3
  dropdownfield: ^1.0.3
  autocomplete_textfield: ^1.7.3
  dropdown_formfield: ^0.1.1
  cached_network_image: ^2.0.0
  cache_image: ^1.0.5
  share: ^0.6.3+4
  firebase_dynamic_links: ^0.5.0+8
  curved_navigation_bar: ^0.3.1
  badges: ^1.1.0
  dynamic_theme: ^1.0.0
  permission_handler: '^4.2.0+hotfix.3'
  random_string: ^2.0.1
  flutter_image_compress: ^0.6.5+1
  image_cropper: ^1.2.1
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.1.6
  intl: ^0.16.1
  flutter_typeahead: ^1.8.0
  photo_view: ^0.9.2
  extended_image: ^0.8.0
  image: any
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.5
  chewie_audio: ^1.0.0+1
  audioplayer: ^0.7.0+1
  audioplayer_web: 0.7.0
  audioplayers: ^0.15.0
  package_info: ^0.4.0+16
  webview_media: ^0.1.1+3
  shared_preferences: ^0.5.6+3
  connectivity: ^0.4.8+2
  pull_to_refresh: ^1.5.7
  readmore: ^1.0.0
  rate_my_app: ^0.6.1+2
  page_transition: ^1.1.5
  url_launcher: ^5.4.10
  loading_gifs: ^0.2.2
  mailer: ^3.0.4
  flutter_email_sender: ^3.0.1
  google_fonts: ^0.3.5
  flutter_facebook_login: ^3.0.0
  characters: ^1.0.0
  flutter_recaptcha_v2: ^0.1.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/img/login_logo.png
   - assets/images/
   - assets/sounds/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
